### ISSUE TITLE
No section named tasks

### ISSUE THREAD

**Issue by mbennehar** [nadav-dav/cygwin-guide#2]
The tutorial says that you have to go to tasks from the preferences menu, however this setting lies under Startup section and is not directly available.

**Comment by nadav-dav** [comment]
hi there! thanks for letting me know.

Unfortunately, i'm not using Windows anymore, hence, not using cygwin.

Where is the button located now?

**Comment by mbennehar** [comment]
It's just a small remark, as you can see from the picture it is located under the Startup section. Thanks for the tutorial by the way, very helpful.
![2016-04-28 18_26_31-conemu 160211 64 settings xml](https://cloud.githubusercontent.com/assets/3809524/14893230/d04004b4-0d6e-11e6-9ca4-15857d97a9c3.png)

**Comment by nadav-dav** [comment]
Fixed! :)

Even added some attribution for you.

Thanks again!
